<?php
  $const = true;
 define('PRODUCTS_OPTIONS_DESCRIPTION_HEADING', 'Beschreibung');
 define('OV_AM_FILE_MAIN_HEADING', 'Eine Datei');
 define('PRODUCTS_OPTIONS_IMAGE_HEADING', 'Ein Bild');
 define('PO_AM_IMAGE_MAIN_HEADING', 'Ein Bild');
 define('PO_AM_FILE_TEST_HEADING', 'Eine Datei');
 define('PO_AM_YESNO_MULTISELECT_HEADING', 'Multiselect');
 define('PO_AM_YESNO_MENGENFELD_HEADING', 'Mengenfeld');
 define('PO_AM_LTEXT_DESCRIPTION_HEADING', 'Beschreibung');
 define('AM_EDIT_OV', 'Bearbeiten');
 define('AM_ADD_OV', 'Mixxxer-Wert hinzuf&uuml;gen');
 define('AM_NEW_OV_HEADING', 'Mixxxer-Wert');
 define('AM_NEW_PO_HEADING', 'Mixxxer-Gruppe');
 define('AM_AC', 'Aktionen');
 define('AM_PP', '+/-');
 define('AM_PR', 'Preis');
 define('AM_WP', '+/-');
 define('AM_WE', 'Gewicht');
 define('AM_ST', 'Lager');
 define('AM_MOD', 'Art.-Nr.');
 define('AM_ORD', 'Reihe');
 define('AM_OPTIONS_VALUES_NAME', 'Name');
 define('AM_NEW_PO', 'Neue Mixxxer-Gruppe');
 define('AM_SAVE', 'Speichern');
 define('AM_YES', 'Ja');
 define('AM_NO', 'Nein');
 define('AM_P2ATTR', 'Artikel als Attribut');
 define('AM_CANCEL_ADD_OV', 'Abbrechen');
 define('AM_CANCEL_NEW_PO', 'Abbrechen');
 define('AM_SHOW_MANAGER', 'Mixxxer Manager anzeigen');
 define('OV_AM_YESNO_IS_PRODUCT_HEADING', "Artikel als Attribut");
 define('AM_SAVE_CURR_ATTR', 'Einstellungen als Profil speichern');
 define('AM_HELP', 'Hilfe');
 define('AM_SAVE_SUCCESS', 'Speichern erfolgreich');
 define('AM_LOAD_SUCCESS', 'Attribute erfolgreich geladen');
 define('AM_LOAD', 'Laden');
 define('AM_LOAD_PROFILE', 'Attribute aus Profil laden');
 define('AM_CANCEL', 'Abbrechen');
 define('AM_SORTORDER', 'Sortierung');
 define('AM_DELETE_SUCCESS', 'Aktion erfolgreich');
 define('AM_DELETE', 'L&ouml;schen');
 define('AM_OPTIONS_GROUP', 'Optionsgruppen');
 define('AM_TITLE', 'Überschrift');
 define('AM_DB_FIELD', 'DB-Feldname');
 define('AM_TYPE', 'Typ');
 define('AM_IMAGE', 'Bild (VARCHAR)');
 define('AM_LONG_TEXT', 'Langer Text (TEXT)');
 define('AM_SHORT_TEXT', 'Kurzer Text (VARCHAR/TEXT)');
 define('AM_YESNO', 'Ja/Nein (BOOL)');
 define('AM_OPTIONS_VALUES', 'Mixxxer-Werte');
 define('AM_NEW_ENTRY', 'Neuer Eintrag');
 define('AM_SUBMIT', 'Absenden');
 define('AM_CONFIG_START', 'Zus&auml;tzliche Felder konfigurieren');
 define('AM_CHECKED', 'Vorauswahl');
 define('MI_PRODUCT', 'Produkt als Optionswert');
 define('AM_MINMAXPRE', 'Min/Max/Vorg.');
 
 
?>
